# apache/my-vhost.conf
<VirtualHost *:80>
    DocumentRoot /var/www/html
    <Directory /var/www/html>
        AllowOverride None
        Order Allow,Deny
        Allow from all
    </Directory>

    # Proxy vers le container PHP (port 9000 par défaut)
    <FilesMatch \.php$>
        SetHandler "proxy:fcgi://php-container:9000"
    </FilesMatch>
</VirtualHost>